apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-app-okteto-backend
spec:
  selector:
    matchLabels:
      app: appointment-app-okteto-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: appointment-app-okteto-backend
    spec:
      containers:
      - name: appointment-app-okteto-backend
        image: pedroantonacio/appointment-app-okteto-backend:latest
        ports:
        - containerPort: 8080